---
- name: Create SnapMirror relationships based on details
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Load SnapMirror details from file
      slurp:
        src: collected_snapmirror_dr_status.yml
      register: snapmirror_file

    - name: Decode SnapMirror details from base64
      set_fact:
        snapmirror_data: "{{ snapmirror_file.content | b64decode | from_yaml }}"

    - name: Extract SnapMirror details
      set_fact:
        snapmirror_details: "{{ snapmirror_data['SnapMirror Details'] }}"

    - name: Debug loaded SnapMirror details
      debug:
        var: snapmirror_details

    - name: Create SnapMirror relationships
      uri:
        url: "https://{{ source_host }}/api/snapmirror/relationships"
        method: POST
        headers:
          Authorization: "Basic {{ (username + ':' + password) | b64encode }}"
          Content-Type: "application/json"
        validate_certs: false
        body:
          source:
            path: "{{ item.destination.path.split(':')[0] }}:{{ item.destination.path.split(':')[-1] }}"
          destination:
            path: "{{ source_vserver }}:{{ item.source.path.split(':')[-1] }}"
          policy: "MirrorAllSnapshotsDiscardNetwork"
        body_format: json
      loop: "{{ snapmirror_details }}"
      register: create_results
      ignore_errors: true

    - name: Debug create results
      debug:
        var: create_results

    - name: Store the results in dr_create.yml
      copy:
        content: |
          SnapMirror Create Results:
          {{ create_results | to_nice_yaml }}
        dest: collected_create_source_snapmirror.yml

