---
- name: Collect and modify CIFS server information
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Get UUID of source Vserver
      uri:
        url: "https://{{ source_host }}/api/svm/svms?name={{ source_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: no
      register: source_vserver_info

    - name: Set source_vserver UUID
      set_fact:
        source_vserver_uuid: "{{ source_vserver_info.json.records[0].uuid }}"

    - name: Delete CIFS server from source Vserver
      uri:
        url: "https://{{ source_host }}/api/protocols/cifs/services/{{ source_vserver_info.json.records[0].uuid }}"
        method: DELETE
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        body_format: json
        body:
          ad_domain.user: "{{ ad_domain_user }}"
          ad_domain.password: "{{ ad_domain_password }}"
          force: true
        validate_certs: false

