---
- name: Create CIFS Server DR Info
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Get UUID of source vserver
      uri:
        url: "https://{{ source_host }}/api/svm/svms?name={{ source_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: false
      register: source_svm_info

    - name: Debug source SVM info
      debug:
        var: source_svm_info

    - name: Get UUID of target vserver
      uri:
        url: "https://{{ target_host }}/api/svm/svms?name={{ target_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: false
      register: target_svm_info

    - name: Debug target SVM info
      debug:
        var: target_svm_info

    - name: Copy contents of collected_source_cifs_server_info.yml to collected_cifs_server_source_to_dr.yml
      command: "cp collected_source_cifs_server_info.yml collected_cifs_server_source_to_dr.yml"
      args:
        creates: "collected_cifs_server_source_to_dr.yml"

    - name: Replace source vserver UUID with target vserver UUID in collected_cifs_server_source_to_dr.yml
      replace:
        path: "collected_cifs_server_source_to_dr.yml"
        regexp: "{{ source_svm_info.json.records[0].uuid }}"
        replace: "{{ target_svm_info.json.records[0].uuid }}"

    - name: Display updated collected_cifs_server_source_to_dr.yml
      command: "cat collected_cifs_server_source_to_dr.yml"


# ---
# - name: Create CIFS Server DR Info
#   hosts: localhost
#   connection: local
#   gather_facts: false

#   vars_files:
#     - vars.yml

#   tasks:
#     - name: Get UUID of source vserver
#       uri:
#         url: "https://{{ source_host }}/api/svm/svms?name={{ source_vserver }}"
#         method: GET
#         headers:
#           Authorization: "{{ auth_header }}"
#           Content-Type: "application/json"
#         validate_certs: false
#       register: source_svm_info

#     - name: Debug source SVM info
#       debug:
#         var: source_svm_info

#     - name: Get UUID of target vserver
#       uri:
#         url: "https://{{ target_host }}/api/svm/svms?name={{ target_vserver }}"
#         method: GET
#         headers:
#           Authorization: "{{ auth_header }}"
#           Content-Type: "application/json"
#         validate_certs: false
#       register: target_svm_info

#     - name: Debug target SVM info
#       debug:
#         var: target_svm_info

#     - name: Copy contents of collected_source_cifs_server_info.yml to collected_cifs_server_source_to_dr.yml
#       command: "cp collected_source_cifs_server_info.yml collected_cifs_server_source_to_dr.yml"
#       args:
#         creates: "collected_cifs_server_source_to_dr.yml"

#     - name: Replace source vserver UUID with target vserver UUID in collected_cifs_server_source_to_dr.yml
#       replace:
#         path: "collected_cifs_server_source_to_dr.yml"
#         regexp: "{{ source_svm_info.json.records[0].uuid }}"
#         replace: "{{ target_svm_info.json.records[0].uuid }}"

#     - name: Display updated collected_cifs_server_source_to_dr.yml
#       command: "cat collected_cifs_server_source_to_dr.yml"